### ISSUE TITLE
SOTF.exe

### ISSUE THREAD

**Issue by GhostAkon** [codengine/SOTFEdit#35] opened 2024-07-10 16:14 UTC
The exe file not showing in the files and was wondering if its just me or if it's something that just missing can I get help on this.

**Comment by codengine** [comment] 2024-07-10 23:57
Is it possible that you have a virus scanner running that removed it?

**Comment by codengine** [comment] 2024-07-10 23:58
Ok closing, as it was resolved at Discord.
Antivirus was the cause.

**Closed by codengine** 2024-07-10 23:58 UTC
